### ISSUE TITLE
cfn-lambda fails on aws-cn partition

### ISSUE THREAD

**Issue by RickKrause** [andrew-templeton/cfn-lambda#26]
Attempted Pull request but was denied...

Use case:  would like lambda to work with aws china.

Following code should fix issue...   alter regex to work with arn:aws-cn:lambda:cn-north-1:000000:function:new-function

Change to index.js

`
function getEnvironment(context) {
  var parsedArn = context.invokedFunctionArn.match(/^arn:aws.*:lambda:(\w+-\w+-\d+):(\d+):function:(.*)$/);
  return {
    LambdaArn: parsedArn[0],
    Region: parsedArn[1],
    AccountId: parsedArn[2],
    LambdaName: parsedArn[3]
  };
}
`

**Comment by andrew-templeton** [comment]
Hi, your PR was merged and deployed to version 2.1.2 of the package on NPM.

Thank you for your commit @RickKrause !
