### ISSUE TITLE
sendResponse now needs parsedUrl.query for the PUT request

### ISSUE THREAD

**Issue by nealeu** [andrew-templeton/cfn-lambda#39]
I'll admit to not having tested, but your code looks to have the same issue as cfn-response at https://github.com/andrew-templeton/cfn-lambda/blob/development/index.js#L235, in that you leave out `parsedUrl.query` from the PUT request URL.

Have you tried against AWS recently?

**Comment by andrew-templeton** [comment]
Pull request? No I have not, have a day job + no updates to this in about 6 months.

**Comment by andrew-templeton** [comment]
@nealeu - Checked what I think you're talking about. I accounted for this in my original design. I think you might misunderstand how the `url.parse` function works. Please see the attached image: 

<img width="823" alt="Screen Shot 2019-06-08 at 1 05 11 AM" src="https://user-images.githubusercontent.com/2443179/59142831-9da6f400-8989-11e9-9562-882569168f06.png">

**Comment by nealeu** [comment]
@andrew-templeton Sorry if your first reply was a reflection of some frustration with me.  Just trying to pass information on.  It is easy for things to get out of date and my frustration is with Amazon not maintaining cfn-response themselves.

It's bizarre.  I was having all sorts of problems and spotted a later implementation using all of parsed URL.  Adding query did the trick.

FWIW, we're on Node 10 for our Lambdas, in case anyone else hits this issue.  I will see if I get chance to do a regression check on Node 8 to see if that change is the problem.

**Comment by andrew-templeton** [comment]
Interesting. It was frustration, but unfair! I had a bad day at work. I owe
you the apology. Thank you for checking it out. Are you still having
issues? I did update it to use the newer version by default with a
parametrized runtime parameter. If it's still an issue I'll definitely get
on it - I was not able to reproduce though?

**Comment by nealeu** [comment]
No apology needed. :)  Those days do happen.

I'll retrofit what I did to a sample stack and give it a go on Monday, so I don't brick the dev environment for several hours.
