### ISSUE TITLE
Node.js 6.10 is deprecated

### ISSUE THREAD

**Issue by eczajk1** [andrew-templeton/cfn-lambda#40]
The Node.js 6.10 runtime is now [deprectated](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) for new lambda functions.

So when I tried to use your launcher page for [cfn-lex-bot](https://github.com/andrew-templeton/cfn-lex-bot), I get the following error in Cloudformation:

![image](https://user-images.githubusercontent.com/2584923/59115904-44eb4300-8918-11e9-96ad-0d2f372bb666.png)

**Comment by andrew-templeton** [comment]
Pull request?

**Comment by andrew-templeton** [comment]
This is being deployed asa breaking change and thus will get a new version identifier

**Comment by andrew-templeton** [comment]
I parametrized this in 4.0.0 which is now live on NPM. Thanks for bringing it to my attention!
