### ISSUE TITLE
Simplify long-running lambdas using waiters

### ISSUE THREAD

**Issue by wjordan** [andrew-templeton/cfn-lambda#9]
Brainstorming a bit: I think the long-running lambda configuration could be simplified by leveraging the [`waitFor`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Service.html#waitFor-property) method in the AWS JavaScript SDK, which implements the 'waiters' API defined in the AWS API JSON documents. For example, the CloudFront [`DistributionDeployed`](https://github.com/aws/aws-sdk-js/blob/7213a8eb4e5ca762f009b0a500f6b2cd27c6e5b9/apis/cloudfront-2016-01-28.waiters2.json#L4-L17) waiter ([`distributionDeployed`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront.html#distributionDeployed-waiter) in the JavaScript SDK) is defined to periodically call the underlying `GetDistribution` (`cloudFront.getDistribution` in the JavaScript SDK) operation every 60 seconds (at most 25 times), returning successfully only when the response path of `Distribution.Status` is equal to `Deployed`. It should be possible to pass these existing waiter names into cfn-lambda and re-use `waitFor` directly, rather than re-implement each waiter from scratch in a custom format. Here's some sample code:

``` js
// `client` is the selected AWS service client instance
// `lambda` is an AWS Lambda client instance
// `event`, `context` are the parameters received by the lambda handler function
// `state` is the waiter state name
    event.waiting = true;  // use this flag to skip create/delete/update action and continue waiting
    client.waitFor(state, params, (err, data) => {
      if (err) error();
      else success();
    });
    setTimeout(() => {
     console.log("Timeout reached, re-executing function");
      lambda.invoke({
        FunctionName: context.invokedFunctionArn,
        InvocationType: 'Event',
        Payload: JSON.stringify(event)
      }, (err, data) => {
        if (err) error();
        else context.done();
      });
    }, context.getRemainingTimeInMillis() - 1000);
```

I have this working in a custom resource I've prototyped without cfn-lambda, and I think it could help simplify the long-running lambda feature in this project quite a bit. Think it's worth developing further into a PR, or are there any things you anticipate wouldn't work correctly with this approach?

**Comment by andrew-templeton** [comment]
I looked long and hard at this, and while I think it's a good one for when this tool is used for a direct creation of an AWS resource. However, a lot of uses I have seen for the kit are for composite resources or completely custom stuff (like firing an HTTP request off as a webhook). 

This would break the use-case for using this for anything but building a singular AWS resource. 
Simple example would be using the long-running approach to spin up a stack in Google or Azure, which obviously would not work with your proposal.

Do you have an approach in mind for how to provide this as a convenience method to users, so they can elect to use this simple method, but are not blocked from writing totally custom, non-AWS related resources? This seems like an excellent candidate for a convenience method we expose.

**Comment by andrew-templeton** [comment]
Poke @wjordan

**Comment by wjordan** [comment]
@andrew-templeton In terms of an optional API that wouldn't break existing use-cases, how about allowing a string to be passed in to the existing `Methods` property, that would be interpreted as the name of an AWS SDK for Node.js waiter to be used instead of a custom function? So an example custom resource definition for an ElastiCache cluster, for which the waiters [`cacheClusterAvailable`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElastiCache.html#cacheClusterAvailable-waiter) and [`cacheClusterDeleted`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElastiCache.html#cacheClusterDeleted-waiter) are already present in the SDK, would look something like:

```
exports.handler = CfnLambda({
  Create: Create,
  Update: Update,
  Delete: Delete,
  NoUpdate: NoUpdate,
  TriggersReplacement: replacementKeys,
  SchemaPath: [__dirname, 'schema.json'],
  LongRunning: {
    LambdaApi: Lambda,
    Methods: {
      Create: 'cacheClusterAvailable',
      Update: 'cacheClusterAvailable',
      Delete: 'cacheClusterDeleted'
    }
  }
});
```

**Comment by andrew-templeton** [comment]
No PR submitted, closing enhancement
